/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;
import Code.Product;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author user
 */
public class GUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUI.class.getName());

    private Product[] products = new Product[100];
    private int productCount = 0;
    
    
    //Addproduct method
    private void addProduct(int code, String name, int quantity, double unitPrice) {
    Product newProduct = new Product(code, name, quantity, unitPrice);

    // Find the correct position to insert alphabetically
    int i = 0;
    while (i < productCount && products[i].getName().compareToIgnoreCase(name) < 0) {
        i++;
    } 

    // Shift right to make space
    for (int j = productCount; j > i; j--) {
        products[j] = products[j - 1];
    }

    // Insert new product
    products[i] = newProduct;
    productCount++;
}

    
//Deletebtn mathod
    private boolean deleteProduct(String name) {
    for (int i = 0; i < productCount; i++) {
        if (products[i].getName().equalsIgnoreCase(name)) {
            // Shift all products after this one to the left
            for (int j = i; j < productCount - 1; j++) {
                products[j] = products[j + 1];
            }
            products[productCount - 1] = null; // Remove reference
            productCount--;
            return true; // Product deleted
        }
    }
    return false; // Product not found
}

// search btn method
   private Product getProduct(String name) {
    for (int i = 0; i < productCount; i++) {
        if (products[i].getName().equalsIgnoreCase(name)) {
            return products[i]; // Found the product
        }
    }
    return null; // Not found
}
 
 //get highest price btn
   private Product getHighestPriceProduct() {
    if (productCount == 0) {
        return null; // No products in the array
    }

    Product highest = products[0];
    for (int i = 1; i < productCount; i++) {
        if (products[i].getUnitPrice() > highest.getUnitPrice()) {
            highest = products[i];
        }
    }
    return highest;
}

   // Update Price
   private boolean updatePrice(String name, double newPrice) {
    for (int i = 0; i < productCount; i++) {
        if (products[i].getName().equalsIgnoreCase(name)) {
            products[i].setUnitPrice(newPrice);
            return true;
        }
    }
    return false;
}
 //update quantity
   private boolean updateQuantity(String name, int newQuantity) {
    for (int i = 0; i < productCount; i++) {
        if (products[i].getName().equalsIgnoreCase(name)) {
            products[i].setQuantity(newQuantity);
            return true;
        }
    }
    return false;
}

    
    
    
    
    
    
    
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCode = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtQuantity = new javax.swing.JTextField();
        txtUnitePrice = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnUp = new javax.swing.JButton();
        btnUq = new javax.swing.JButton();
        btnHp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Code:");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Name:");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Quantity:");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("UnitPrice:");

        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setForeground(new java.awt.Color(0, 0, 0));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setForeground(new java.awt.Color(0, 0, 0));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        btnUp.setForeground(new java.awt.Color(0, 0, 0));
        btnUp.setText("Update Price");
        btnUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpActionPerformed(evt);
            }
        });

        btnUq.setForeground(new java.awt.Color(0, 0, 0));
        btnUq.setText("Update Quantity");
        btnUq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUqActionPerformed(evt);
            }
        });

        btnHp.setForeground(new java.awt.Color(0, 0, 0));
        btnHp.setText("Get Highest Price");
        btnHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCode)
                            .addComponent(txtQuantity)
                            .addComponent(txtName)
                            .addComponent(txtUnitePrice, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(29, 29, 29)
                        .addComponent(btnDelete)
                        .addGap(38, 38, 38)
                        .addComponent(btnSearch)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUq)
                    .addComponent(btnUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUq))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtUnitePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUp))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete)
                    .addComponent(btnSearch)
                    .addComponent(btnHp))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHpActionPerformed
        
      Product highest = getHighestPriceProduct();

    if (highest != null) {
        txtCode.setText(String.valueOf(highest.getCode()));
        txtName.setText(highest.getName());
        txtQuantity.setText(String.valueOf(highest.getQuantity()));
        txtUnitePrice.setText(String.valueOf(highest.getUnitPrice()));
        JOptionPane.showMessageDialog(this, "Highest price product loaded.");
    } else {
        JOptionPane.showMessageDialog(this, "No products in the inventory.");
    }  
              
        
    }//GEN-LAST:event_btnHpActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       
        try {
        int code = Integer.parseInt(txtCode.getText().trim());
        String name = txtName.getText().trim();
        int quantity = Integer.parseInt(txtQuantity.getText().trim());
        double unitPrice = Double.parseDouble(txtUnitePrice.getText().trim());

        addProduct(code, name, quantity, unitPrice);  //  This calls your method

        JOptionPane.showMessageDialog(this, "Product added successfully!");

        // Clear fields
        txtCode.setText("");
        txtName.setText("");
        txtQuantity.setText("");
        txtUnitePrice.setText("");

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid input. Please enter correct values.");
    }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
    String nameToDelete = txtName.getText().trim();

    if (nameToDelete.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a product name to delete.");
        return;
    }

    boolean deleted = deleteProduct(nameToDelete);
    if (deleted) {
        JOptionPane.showMessageDialog(this, "Product deleted successfully.");
    } else {
        JOptionPane.showMessageDialog(this, "Product not found.");
    }

    // Clear text fields
    txtCode.setText("");
    txtName.setText("");
    txtQuantity.setText("");
    txtUnitePrice.setText("");


    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String nameToSearch = txtName.getText().trim();

    if (nameToSearch.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter a product name to search.");
        return;
    }

    Product result = getProduct(nameToSearch);
    if (result != null) {
        txtCode.setText(String.valueOf(result.getCode()));
        txtQuantity.setText(String.valueOf(result.getQuantity()));
        txtUnitePrice.setText(String.valueOf(result.getUnitPrice()));
        JOptionPane.showMessageDialog(this, "Product found.");
    } else {
        JOptionPane.showMessageDialog(this, "Product not found.");
        txtCode.setText("");
        txtQuantity.setText("");
        txtUnitePrice.setText("");
    }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpActionPerformed
        String name = txtName.getText().trim();
    String newPriceStr = txtUnitePrice.getText().trim();

    if (name.isEmpty() || newPriceStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter product name and new price.");
        return;
    }

    try {
        double newPrice = Double.parseDouble(newPriceStr);
        boolean updated = updatePrice(name, newPrice);
        if (updated) {
            JOptionPane.showMessageDialog(this, "Price updated successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Product not found.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid price format.");
    }
    }//GEN-LAST:event_btnUpActionPerformed

    private void btnUqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUqActionPerformed
           String name = txtName.getText().trim();
    String quantityStr = txtQuantity.getText().trim();

    if (name.isEmpty() || quantityStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Enter product name and new quantity.");
        return;
    }

    try {
        int newQuantity = Integer.parseInt(quantityStr);
        boolean updated = updateQuantity(name, newQuantity);
        if (updated) {
            JOptionPane.showMessageDialog(this, "Quantity updated successfully.");
        } else {
            JOptionPane.showMessageDialog(this, "Product not found.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid quantity format.");
    }

    }//GEN-LAST:event_btnUqActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHp;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUp;
    private javax.swing.JButton btnUq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtUnitePrice;
    // End of variables declaration//GEN-END:variables
}
